windows_fields_mapping = {
    "AccountName": "user.name",
    "AccountDomain": "user.domain",
    "ClientAddress": "source.ip",
    "ClientName": "source.domain",
    "LogonID": "logon.id",
    "TargetUserSid": "user.id",
    "TargetUserName": "user.name",
    "TargetDomainName": "user.domain",
    "IpAddress": "source.ip",
    "IpPort": "source.port",
    "WorkstationName": "source.domain",
    "NewProcessId": "process.pid",
    "NewProcessName": "process.executable",
    "ProcessName": "process.executable",
    "ParentProcessName": "process.parent.executable"
}


sysmon_fields_mapping = {
    "UtcTime": "@timestamp",
    "ProcessGuid": "process.entity_id",
    "ProcessId": "process.pid",
    "Image": "process.executable",
    "CommandLine": "process.command_line",
    "CurrentDirectory": "process.working_directory",
    "ParentProcessGuid": "process.parent.entity_id",
    "ParentProcessId": "process.parent.pid",
    "ParentImage": "process.parent.executable",
    "ParentCommandLine": "process.parent.command_line",
    "TargetFilename": "file.path",
    "Protocol": "network.transport",
    "SourceIp": "source.ip",
    "SourceHostname": "source.domain",
    "SourcePort": "source.port",
    "DestinationIp": "destination.ip",
    "DestinationHostname": "destination.domain",
    "DestinationPort": "destination.port",
    "DestinationPortName": "network.protocol",
    "ImageLoaded": "file.path",
    "Signature": "file.code_signature.subject_name",
    "SignatureStatus": "file.code_signature.status",
    "SourceProcessGuid": "process.entity_id",
    "SourceProcessId": "process.pid",
    "SourceImage": "process.executable",
    "Device": "file.path",
    "SourceThreadId": "process.thread.id",
    "PipeName": "file.name",
    "Destination": "process.executable",
    "QueryName": "dns.question.name",
    "QueryStatus": "sysmon.dns.status",
    "RuleName": "rule.name",
    "Archived": "sysmon.file.archived",
    "IsExecutable": "sysmon.file.is_executable",
    "ID": "error.code"
}

common_registry_hives = {
    "HKEY_CLASSES_ROOT": "HKCR",
    "HKCR": "HKCR",
    "HKEY_CURRENT_CONFIG": "HKCC",
    "HKCC": "HKCC",
    "HKEY_CURRENT_USER": "HKCU",
    "HKCU": "HKCU",
    "HKEY_DYN_DATA": "HKDD",
    "HKDD": "HKDD",
    "HKEY_LOCAL_MACHINE": "HKLM",
    "HKLM": "HKLM",
    "HKEY_PERFORMANCE_DATA": "HKPD",
    "HKPD": "HKPD",
    "HKEY_USERS": "HKU",
    "HKU": "HKU"
}